import 'package:base_project/data/model/models.dart';
import 'package:base_project/data/repository/repositories.dart';
import 'package:base_project/ui/pages/auth/bloc/auth_bloc.dart';
import 'package:base_project/ui/pages/home/bloc/home_bloc.dart';
import 'package:base_project/ui/widgets/alert_dialog.dart';
import 'package:base_project/ui/widgets/widgets.dart';
import 'package:base_project/util/themes.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:base_project/util/globalvar.dart' as globals;

part 'splash_page.dart';
part 'main_page.dart';
part 'home/home_page.dart';
part 'bookmark/bookmark_page.dart';
part 'message/message_page.dart';
part 'profile/profile_page.dart';
part 'job/job_detail_page.dart';
part 'auth/login_page.dart';
part 'auth/signup_page.dart';
